[package]
name = "serde_and_borsh"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "Borsh"
path = "src/Borsh.rs"


[dependencies]
borsh = {version="1.5.7", features = ["derive"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
